CREATE TABLE TEMPO (
    ID_TEMPO NUMBER,
    DIA NUMBER(2) NOT NULL,
    MES NUMBER(2) NOT NULL,
    ANO NUMBER(4) NOT NULL,
    TRIM NUMBER(1) NOT NULL,
    CONSTRAINT PK_TEMPO PRIMARY KEY (ID_TEMPO)
);

CREATE SEQUENCE SEQ_TEMPO NOCACHE NOCYCLE;

CREATE TABLE CURSO (
    ID_CURSO NUMBER,
    DESCRICAO VARCHAR2(200),
    CONSTRAINT PK_CURSO PRIMARY KEY (ID_CURSO)
);

CREATE SEQUENCE SEQ_CURSO NOCACHE NOCYCLE;

CREATE TABLE PERIODO (
    ID_PERIODO NUMBER,
    DESCRICAO VARCHAR2(250) NOT NULL,
     CONSTRAINT PK_PERIODO PRIMARY KEY (ID_PERIODO)
);

CREATE SEQUENCE SEQ_PERIODO NOCACHE NOCYCLE;

CREATE TABLE FAIXA_ETARIA (
    ID_FAIXA NUMBER,
    DESCRICAO VARCHAR2(150) NOT NULL,
    CONSTRAINT PK_FAIXA PRIMARY KEY (ID_FAIXA)
);

CREATE SEQUENCE SEQ_FAIXA NOCACHE NOCYCLE;


CREATE TABLE FATURAMENTO (
    ID_TEMPO NUMBER,
    ID_CURSO NUMBER,
    TIPO_ALUNO CHAR(1),
    QTD NUMBER,
    VALOR NUMBER(7,2),
    CONSTRAINT FK_FATURAMENTO_TEMPO FOREIGN KEY (ID_TEMPO) REFERENCES TEMPO (ID_TEMPO),
    CONSTRAINT FK_FATURAMENTO_CURSO FOREIGN KEY (ID_CURSO) REFERENCES CURSO (ID_CURSO),
);

CREATE TABLE DESISTENCIA (
    ID_TEMPO NUMBER,
    ID_CURSO NUMBER,
    ID_PERIODO NUMBER,
    TIPO_ALUNO CHAR(1),
    GENERO CHAR(1),
    ID_FAIXA NUMBER,
    CAPTACAO VARCHAR2(150),
    ESCOLARIDADE VARCHAR2(150)
    QTD NUMBER,
    CONSTRAINT FK_DESISTENCIA_TEMPO FOREIGN KEY (ID_TEMPO) REFERENCES TEMPO (ID_TEMPO),
    CONSTRAINT FK_DESISTENCIA_CURSO FOREIGN KEY (ID_CURSO) REFERENCES CURSO (ID_CURSO),
    CONSTRAINT FK_DESISTENCIA_PERIODO FOREIGN KEY (ID_PERIODO) REFERENCES LOCAL (ID_LOCAL),
    CONSTRAINT FK_DESISTENCIA_FAIXA_ETARIA FOREIGN KEY (ID_FAIXA) REFERENCES FAIXA_ETARIA (ID_FAIXA),
    
);