-- RESET
DROP TABLE HOSPEDAGEM;
DROP TABLE SERVICO;
DROP TABLE TEMPO;
DROP TABLE MOTIVO_VIAGEM;
DROP TABLE PROFISSAO;
DROP TABLE AGENCIA;
DROP TABLE SERVICO;
DROP TABLE PRODUTO;

DROP SEQUENCE SEQ_TEMPO;
DROP SEQUENCE SEQ_MOTIVO;
DROP SEQUENCE SEQ_PROFISSAO
DROP SEQUENCE SEQ_AGENCIA;
DROP SEQUENCE SEQ_TPSERVICO;

-- TABELAS "HOSPEDAGEMS"
CREATE TABLE TEMPO (
  ID_TEMPO NUMBER(5) PRIMARY KEY,
  ANO NUMBER(4) NOT NULL,
  MES NUMBER(2) NOT NULL,
  TRIMESTRE NUMBER(1) NOT NULL
);

CREATE TABLE MOTIVO_VIAGEM (
  ID_MOTIVO NUMBER(5) PRIMARY KEY,
  DESCRICAO VARCHAR2(100) NOT NULL
);

CREATE TABLE PROFISSAO (
  ID_PROFISSAO NUMBER(5) PRIMARY KEY,
  DESCRICAO VARCHAR2(100) NOT NULL
);

CREATE TABLE AGENCIA (
  ID_AGENCIA NUMBER(5) PRIMARY KEY,
  NOME VARCHAR2(100) NOT NULL
);

CREATE TABLE HOSPEDAGEM (
    ID_TEMPO NUMBER(5) NOT NULL,
    ID_MOTIVO NUMBER(5) NOT NULL,
    ID_PROFISSAO NUMBER(5) NOT NULL,
    ID_AGENCIA NUMBER(5) NOT NULL,
    TIPO_APARTAMENTO VARCHAR2(80) NOT NULL,
    MEIO_TRANSPORTE VARCHAR2(80) NOT NULL,
    QNT_DIAS NUMBER(2) NOT NULL,
    VALOR DECIMAL(10,2) NOT NULL,

    CONSTRAINT PK_HOSPEDAGEM PRIMARY KEY (ID_TEMPO, ID_MOTIVO, ID_PROFISSAO, ID_AGENCIA), 
    CONSTRAINT FK_HOSPEDAGEM_TEMPO FOREIGN KEY (ID_TEMPO) REFERENCES TEMPO (ID_TEMPO),
    CONSTRAINT FK_HOSPEDAGEM_MOTIVO FOREIGN KEY (ID_MOTIVO) REFERENCES MOTIVO_VIAGEM (ID_MOTIVO),
    CONSTRAINT FK_HOSPEDAGEM_PROFISSAO FOREIGN KEY (ID_PROFISSAO) REFERENCES PROFISSAO (ID_PROFISSAO),
    CONSTRAINT FK_HOSPEDAGEM_AGENCIA FOREIGN KEY (ID_AGENCIA) REFERENCES AGENCIA (ID_AGENCIA),

    CONSTRAINT CK_TIPO_APARTAMENTO CHECK (TIPO_APARTAMENTO IN ('Simples', 'Duplo', 'Suite', 'Suite Presidencial')),
    CONSTRAINT CK_MEIO_TRANSPORTE CHECK (MEIO_TRANSPORTE IN ('Carro', 'Aviao', 'Barco'))
);

-- TABELAS "CONSUMO"
CREATE TABLE SERVICO (
    ID_SERVICO NUMBER(5) PRIMARY KEY,
    DESCRICAO VARCHAR2(100) NOT NULL
);

CREATE TABLE PRODUTO (
    ID_PRODUTO NUMBER(5) PRIMARY KEY,
    DESCRICAO VARCHAR2(100) NOT NULL
);

-- TABELAS DE FATO "SERVICO"
  CREATE TABLE CONSUMO (
  ID_TEMPO NUMBER(5) NOT NULL,
  ID_MOTIVO NUMBER(5) NOT NULL,
  ID_SERVICO NUMBER(5) NOT NULL,
  ID_PRODUTO NUMBER(5) NOT NULL,
  VALOR_SERVICO DECIMAL(10,2) NOT NULL,
  VALOR_PRODUTO DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (ID_TEMPO, ID_SERVICO, ID_PRODUTO),
  CONSTRAINT FK_SERVICO_TEMPO FOREIGN KEY (ID_TEMPO) REFERENCES TEMPO (ID_TEMPO),
  CONSTRAINT FK_SERVICO_TIPO FOREIGN KEY (ID_SERVICO) REFERENCES SERVICO (ID_SERVICO),
  CONSTRAINT FK_SERVICO_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO (ID_PRODUTO),
  CONSTRAINT FK_CONSUMO_MOTIVO FOREIGN KEY (ID_MOTIVO) REFERENCES MOTIVO_VIAGEM (ID_MOTIVO)

);

-- VARIÁVEIS DE INTERVALOS
CREATE SEQUENCE SEQ_TEMPO START WITH 1 INCREMENT BY 1 MAXVALUE 99999 NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_MOTIVO START WITH 1 INCREMENT BY 1 MAXVALUE 99999 NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_PROFISSAO START WITH 1 INCREMENT BY 1 MAXVALUE 99999 NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_AGENCIA START WITH 1 INCREMENT BY 1 MAXVALUE 99999 NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_SERVICO START WITH 1 INCREMENT BY 1 MAXVALUE 99999 NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_PRODUTO START WITH 1 INCREMENT BY 1 MAXVALUE 99999 NOCYCLE NOCACHE;

-- INSERINDO DADOS
INSERT INTO TEMPO (ID_TEMPO, ANO, MES, TRIMESTRE) VALUES (SEQ_TEMPO.NEXTVAL, 2022, 01, 1);
INSERT INTO TEMPO (ID_TEMPO, ANO, MES, TRIMESTRE) VALUES (SEQ_TEMPO.NEXTVAL, 2022, 05, 2);
INSERT INTO TEMPO (ID_TEMPO, ANO, MES, TRIMESTRE) VALUES (SEQ_TEMPO.NEXTVAL, 2022, 08, 3);
INSERT INTO TEMPO (ID_TEMPO, ANO, MES, TRIMESTRE) VALUES (SEQ_TEMPO.NEXTVAL, 2022, 12, 4);

INSERT INTO MOTIVO_VIAGEM (ID_MOTIVO, DESCRICAO) VALUES (SEQ_MOTIVO.NEXTVAL, 'Negocios');
INSERT INTO MOTIVO_VIAGEM (ID_MOTIVO, DESCRICAO) VALUES (SEQ_MOTIVO.NEXTVAL, 'Turismo');

INSERT INTO PROFISSAO (ID_PROFISSAO, DESCRICAO) VALUES (SEQ_PROFISSAO.NEXTVAL, 'Programador');
INSERT INTO PROFISSAO (ID_PROFISSAO, DESCRICAO) VALUES (SEQ_PROFISSAO.NEXTVAL, 'Professor');
INSERT INTO PROFISSAO (ID_PROFISSAO, DESCRICAO) VALUES (SEQ_PROFISSAO.NEXTVAL, 'Enfermeiro');
INSERT INTO PROFISSAO (ID_PROFISSAO, DESCRICAO) VALUES (SEQ_PROFISSAO.NEXTVAL, 'Desempregado');

INSERT INTO AGENCIA (ID_AGENCIA, NOME) VALUES (SEQ_AGENCIA.NEXTVAL, 'Sem agencia');
INSERT INTO AGENCIA (ID_AGENCIA, NOME) VALUES (SEQ_AGENCIA.NEXTVAL, 'Hostelworld');
INSERT INTO AGENCIA (ID_AGENCIA, NOME) VALUES (SEQ_AGENCIA.NEXTVAL, 'Agoda');
INSERT INTO AGENCIA (ID_AGENCIA, NOME) VALUES (SEQ_AGENCIA.NEXTVAL, 'Expedia');

INSERT INTO SERVICO (ID_SERVICO, DESCRICAO) VALUES (SEQ_SERVICO.NEXTVAL, 'Restaurante');
INSERT INTO SERVICO (ID_SERVICO, DESCRICAO) VALUES (SEQ_SERVICO.NEXTVAL, 'Bar');
INSERT INTO SERVICO (ID_SERVICO, DESCRICAO) VALUES (SEQ_SERVICO.NEXTVAL, 'Sauna');
INSERT INTO SERVICO (ID_SERVICO, DESCRICAO) VALUES (SEQ_SERVICO.NEXTVAL, 'Piscina');
INSERT INTO SERVICO (ID_SERVICO, DESCRICAO) VALUES (SEQ_SERVICO.NEXTVAL, 'Salao de beleza');
INSERT INTO SERVICO (ID_SERVICO, DESCRICAO) VALUES (SEQ_SERVICO.NEXTVAL, 'Loja de presentes');
INSERT INTO SERVICO (ID_SERVICO, DESCRICAO) VALUES (SEQ_SERVICO.NEXTVAL, 'Lavanderia');
INSERT INTO SERVICO (ID_SERVICO, DESCRICAO) VALUES (SEQ_SERVICO.NEXTVAL, 'Copa');
INSERT INTO SERVICO (ID_SERVICO, DESCRICAO) VALUES (SEQ_SERVICO.NEXTVAL, 'Nenhum servico pedido');


INSERT INTO PRODUTO (ID_PRODUTO, DESCRICAO) VALUES (SEQ_PRODUTO.NEXTVAL, 'Frigobar');
INSERT INTO PRODUTO (ID_PRODUTO, DESCRICAO) VALUES (SEQ_PRODUTO.NEXTVAL, 'Bebidas');
INSERT INTO PRODUTO (ID_PRODUTO, DESCRICAO) VALUES (SEQ_PRODUTO.NEXTVAL, 'Alimentos');
INSERT INTO PRODUTO (ID_PRODUTO, DESCRICAO) VALUES (SEQ_PRODUTO.NEXTVAL, 'Servico de quarto');
INSERT INTO PRODUTO (ID_PRODUTO, DESCRICAO) VALUES (SEQ_PRODUTO.NEXTVAL, 'Nenhum consumo pedido');


INSERT INTO HOSPEDAGEM (ID_TEMPO, ID_MOTIVO, MEIO_TRANSPORTE, TIPO_APARTAMENTO, ID_PROFISSAO, ID_AGENCIA, QNT_DIAS, VALOR)
            VALUES (1,1,'Carro','Simples',1,1,2,300.00);

INSERT INTO HOSPEDAGEM (ID_TEMPO, ID_MOTIVO, MEIO_TRANSPORTE, TIPO_APARTAMENTO, ID_PROFISSAO, ID_AGENCIA, QNT_DIAS, VALOR)
            VALUES (1,1,'Aviao','Suite',2,1,5,300.00);

INSERT INTO HOSPEDAGEM (ID_TEMPO, ID_MOTIVO, MEIO_TRANSPORTE, TIPO_APARTAMENTO, ID_PROFISSAO, ID_AGENCIA, QNT_DIAS, VALOR)
            VALUES (2,2,'Carro','Duplo',1,2,5,300.00);

INSERT INTO HOSPEDAGEM (ID_TEMPO, ID_MOTIVO, MEIO_TRANSPORTE, TIPO_APARTAMENTO, ID_PROFISSAO, ID_AGENCIA, QNT_DIAS, VALOR)
            VALUES (3,1,'Aviao','Suite Presidencial',3,2,2,300.00);

INSERT INTO HOSPEDAGEM (ID_TEMPO, ID_MOTIVO, MEIO_TRANSPORTE, TIPO_APARTAMENTO, ID_PROFISSAO, ID_AGENCIA, QNT_DIAS, VALOR)
            VALUES (4,2,'Barco','Duplo',2,3,10,300.00);


INSERT INTO CONSUMO (ID_TEMPO, ID_MOTIVO, ID_SERVICO, ID_PRODUTO, VALOR_SERVICO, VALOR_PRODUTO)
            VALUES (4,1,1,1,2.00,1.00);

INSERT INTO CONSUMO (ID_TEMPO, ID_MOTIVO, ID_SERVICO, ID_PRODUTO, VALOR_SERVICO, VALOR_PRODUTO)
            VALUES (1,1,2,2,2.00,1.00);

INSERT INTO CONSUMO (ID_TEMPO, ID_MOTIVO, ID_SERVICO, ID_PRODUTO, VALOR_SERVICO, VALOR_PRODUTO)
            VALUES (2,2,1,3,2.00,1.00);


-- SELECTS
-- Visualizar ao longo do tempo, com divisão por mês, o faturamento por motivo de viagem e meio de transporte.
SELECT TEMPO.MES"MES", MOTIVO_VIAGEM.DESCRICAO"MOTIVO DA VIAGEM", HOSPEDAGEM.MEIO_TRANSPORTE"MEIO DE TRANSPORTE", SUM(HOSPEDAGEM.VALOR) AS "FAT. TOTAL (R$)"
FROM HOSPEDAGEM
JOIN TEMPO ON HOSPEDAGEM.ID_TEMPO = TEMPO.ID_TEMPO
JOIN MOTIVO_VIAGEM ON HOSPEDAGEM.ID_MOTIVO = MOTIVO_VIAGEM.ID_MOTIVO
GROUP BY TEMPO.MES, ROLLUP(MOTIVO_VIAGEM.DESCRICAO, HOSPEDAGEM.MEIO_TRANSPORTE);

-- Evolução do faturamento por tipo de apartamento por trimestre.
SELECT TEMPO.TRIMESTRE,HOSPEDAGEM.TIPO_APARTAMENTO"TIPO DO APARTAMENTO", SUM(HOSPEDAGEM.VALOR) AS "FAT. TOTAL (R$)"
FROM HOSPEDAGEM
JOIN TEMPO ON HOSPEDAGEM.ID_TEMPO = TEMPO.ID_TEMPO
GROUP BY TEMPO.TRIMESTRE, ROLLUP(HOSPEDAGEM.TIPO_APARTAMENTO);

-- Faturamento de serviços com consumo de bebidas e alimentos em reais por tipo de serviço.
SELECT PRODUTO.DESCRICAO"CONSUMO DE SERVICO", SUM(CONSUMO.VALOR_PRODUTO) AS "FAT. TOTAL (R$)"
FROM CONSUMO
JOIN PRODUTO ON CONSUMO.ID_PRODUTO = PRODUTO.ID_PRODUTO
WHERE PRODUTO.DESCRICAO IN ('Bebidas', 'Alimentos')
GROUP BY CUBE(PRODUTO.DESCRICAO);

-- Faturamento por profissão de hóspede.
SELECT PROFISSAO.DESCRICAO"PROFISSAO", SUM(HOSPEDAGEM.VALOR) AS "FAT. TOTAL (R$)"
FROM HOSPEDAGEM
JOIN PROFISSAO ON HOSPEDAGEM.ID_PROFISSAO = PROFISSAO.ID_PROFISSAO
GROUP BY CUBE (PROFISSAO.DESCRICAO);

-- Faturamento por agências.
SELECT AGENCIA.NOME, SUM(HOSPEDAGEM.VALOR)
FROM HOSPEDAGEM
JOIN AGENCIA ON HOSPEDAGEM.ID_AGENCIA = AGENCIA.ID_AGENCIA
GROUP BY CUBE(AGENCIA.NOME);

-- Faturamento por viagem de negócios, distribuído em diárias e consumos de frigobar.
SELECT  TEMPO.MES,
        SUM(HOSPEDAGEM.QNT_DIAS * HOSPEDAGEM.VALOR) AS "DIARIA (R$)",
        SUM(CONSUMO.VALOR_PRODUTO) AS "CONSUMO (R$)",
        SUM((HOSPEDAGEM.QNT_DIAS * HOSPEDAGEM.VALOR)+CONSUMO.VALOR_PRODUTO) AS "TOTAL (R$)"
FROM CONSUMO
JOIN TEMPO ON CONSUMO.ID_TEMPO = TEMPO.ID_TEMPO
JOIN MOTIVO_VIAGEM ON CONSUMO.ID_MOTIVO = MOTIVO_VIAGEM.ID_MOTIVO
JOIN HOSPEDAGEM ON HOSPEDAGEM.ID_MOTIVO = MOTIVO_VIAGEM.ID_MOTIVO
WHERE MOTIVO_VIAGEM.DESCRICAO = 'Negocios'
GROUP BY TEMPO.MES, ROLLUP(HOSPEDAGEM.QNT_DIAS * HOSPEDAGEM.VALOR, CONSUMO.VALOR_PRODUTO, (HOSPEDAGEM.QNT_DIAS * HOSPEDAGEM.VALOR)+CONSUMO.VALOR_PRODUTO);