-- Limpar base de dados
DROP SEQUENCE "SEQ_CINEMA";
DROP SEQUENCE "SEQ_LOCAL";
DROP SEQUENCE "SEQ_ATOR";
DROP SEQUENCE "SEQ_DIRETOR";
DROP SEQUENCE "SEQ_GENERO";

DROP TABLE "EXIBICAO";
DROP TABLE "CINEMA";
DROP TABLE "LOCAL";
DROP TABLE "TEMPO";
DROP TABLE "ATOR";
DROP TABLE "DIRETOR";
DROP TABLE "GENERO";


-- Criação das tabelas
CREATE TABLE CINEMA(
    ID_CINEMA NUMBER(5) PRIMARY KEY,
    NOME_CINE VARCHAR2(120) NOT NULL
);

CREATE TABLE LOCAL(
    ID_LOCAL NUMBER(5) PRIMARY KEY,
    CIDADE VARCHAR2(120) NOT NULL,
    ESTADO CHAR(2) NOT NULL,
	REGIAO VARCHAR2(20) NOT NULL, 
    PAIS VARCHAR2(3) NOT NULL 
);

CREATE TABLE TEMPO(
    DIA NUMBER(2) NOT NULL,
	MES NUMBER(2) NOT NULL,
	ANO NUMBER(4) NOT NULL,
	PRIMARY KEY (DIA,MES,ANO)

);

CREATE TABLE ATOR(
    ID_ATOR NUMBER(5) PRIMARY KEY,
    NOME_ATOR VARCHAR2(120) NOT NULL
);

CREATE TABLE DIRETOR(
    ID_DIRETOR NUMBER(5) PRIMARY KEY,
    NOME_DIR VARCHAR2(120) NOT NULL
);

CREATE TABLE GENERO(
    ID_GENERO NUMBER(5) PRIMARY KEY,
    DESCRICAO VARCHAR2(120) NOT NULL
);

CREATE TABLE EXIBICAO(
    ID_CINEMA NUMBER(5),
    ID_LOCAL NUMBER(5),
    ID_ATOR NUMBER(5),
    ID_DIRETOR NUMBER(5),
    ID_GENERO NUMBER(5),
	QUANTIDADE NUMBER(6) NULL,
    VALOR NUMBER(7,2) NOT NULL,
    DIA NUMBER(2) NOT NULL,
	MES NUMBER(2) NOT NULL,
	ANO NUMBER(4) NOT NULL,
	CONSTRAINT PK_EXIBICAO 			PRIMARY KEY (ID_CINEMA, ID_LOCAL, ID_ATOR, ID_DIRETOR, ID_GENERO), 
	CONSTRAINT FK_EXIBICAO_CINEMA 	FOREIGN KEY (ID_CINEMA)		REFERENCES CINEMA (ID_CINEMA),
	CONSTRAINT FK_EXIBICAO_LOCAL 	FOREIGN KEY (ID_LOCAL)		REFERENCES LOCAL (ID_LOCAL),
	CONSTRAINT FK_EXIBICAO_ATOR 	FOREIGN KEY (ID_ATOR)		REFERENCES ATOR (ID_ATOR),
	CONSTRAINT FK_EXIBICAO_DIRETOR 	FOREIGN KEY (ID_DIRETOR)	REFERENCES DIRETOR (ID_DIRETOR),
	CONSTRAINT FK_EXIBICAO_GENERO 	FOREIGN KEY (ID_GENERO)		REFERENCES GENERO (ID_GENERO),
    CONSTRAINT FK_EXIBICAO_TEMPO    FOREIGN KEY (DIA,MES,ANO)   REFERENCES TEMPO(DIA,MES,ANO)
);

-- Criação dos intervalos
CREATE SEQUENCE SEQ_CINEMA START WITH 1 INCREMENT BY 1 MAXVALUE 99999 NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_LOCAL START WITH 1 INCREMENT BY 1 MAXVALUE 99999 NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_ATOR START WITH 1 INCREMENT BY 1 MAXVALUE 99999 NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_DIRETOR START WITH 1 INCREMENT BY 1 MAXVALUE 99999 NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_GENERO START WITH 1 INCREMENT BY 1 MAXVALUE 99999 NOCYCLE NOCACHE;

---- Iserção de dados
INSERT INTO CINEMA (ID_CINEMA, NOME_CINE) VALUES (SEQ_CINEMA.NEXTVAL, 'CINE_MANAUS');
INSERT INTO CINEMA (ID_CINEMA, NOME_CINE) VALUES (SEQ_CINEMA.NEXTVAL, 'CINE_RIO BRANCO');
INSERT INTO CINEMA (ID_CINEMA, NOME_CINE) VALUES (SEQ_CINEMA.NEXTVAL, 'CINE_SALVADOR');
INSERT INTO CINEMA (ID_CINEMA, NOME_CINE) VALUES (SEQ_CINEMA.NEXTVAL, 'CINE_FORTALEZA');
INSERT INTO CINEMA (ID_CINEMA, NOME_CINE) VALUES (SEQ_CINEMA.NEXTVAL, 'CINE_BRASILIA ');
INSERT INTO CINEMA (ID_CINEMA, NOME_CINE) VALUES (SEQ_CINEMA.NEXTVAL, 'CINE_CUIABÁ');
INSERT INTO CINEMA (ID_CINEMA, NOME_CINE) VALUES (SEQ_CINEMA.NEXTVAL, 'CINE_SÃO PAULO');
INSERT INTO CINEMA (ID_CINEMA, NOME_CINE) VALUES (SEQ_CINEMA.NEXTVAL, 'CINE_BELO HORIZONTE');
INSERT INTO CINEMA (ID_CINEMA, NOME_CINE) VALUES (SEQ_CINEMA.NEXTVAL, 'CINE_CURITIBA');
INSERT INTO CINEMA (ID_CINEMA, NOME_CINE) VALUES (SEQ_CINEMA.NEXTVAL, 'CINE_FLORIANÓPOLIS');


INSERT INTO LOCAL (ID_LOCAL, CIDADE, ESTADO, REGIAO, PAIS) VALUES (SEQ_LOCAL.NEXTVAL, 'MANAUS', 'AM', 'NORTE', 'BR');
INSERT INTO LOCAL (ID_LOCAL, CIDADE, ESTADO, REGIAO, PAIS) VALUES (SEQ_LOCAL.NEXTVAL, 'RIO BRANCO', 'AC', 'NORTE', 'BR');
INSERT INTO LOCAL (ID_LOCAL, CIDADE, ESTADO, REGIAO, PAIS) VALUES (SEQ_LOCAL.NEXTVAL, 'SALVADOR', 'BA', 'NORDESTE', 'BR');
INSERT INTO LOCAL (ID_LOCAL, CIDADE, ESTADO, REGIAO, PAIS) VALUES (SEQ_LOCAL.NEXTVAL, 'FORTALEZA', 'CE', 'NORDESTE', 'BR');
INSERT INTO LOCAL (ID_LOCAL, CIDADE, ESTADO, REGIAO, PAIS) VALUES (SEQ_LOCAL.NEXTVAL, 'BRASÍLIA', 'DF', 'CENTRO-OESTE', 'BR');
INSERT INTO LOCAL (ID_LOCAL, CIDADE, ESTADO, REGIAO, PAIS) VALUES (SEQ_LOCAL.NEXTVAL, 'CUIABÁ', 'MA', 'CENTRO-OESTE', 'BR');
INSERT INTO LOCAL (ID_LOCAL, CIDADE, ESTADO, REGIAO, PAIS) VALUES (SEQ_LOCAL.NEXTVAL, 'SÃO PAULO', 'SP', 'SUDESTE', 'BR');
INSERT INTO LOCAL (ID_LOCAL, CIDADE, ESTADO, REGIAO, PAIS) VALUES (SEQ_LOCAL.NEXTVAL, 'BELO HORIZONTE', 'MG', 'SUDESTE', 'BR');
INSERT INTO LOCAL (ID_LOCAL, CIDADE, ESTADO, REGIAO, PAIS) VALUES (SEQ_LOCAL.NEXTVAL, 'CURITIBA', 'PR', 'SUL', 'BR');
INSERT INTO LOCAL (ID_LOCAL, CIDADE, ESTADO, REGIAO, PAIS) VALUES (SEQ_LOCAL.NEXTVAL, 'FLORIANÓPOLIS', 'SC', 'SUL', 'BR');


INSERT INTO ATOR (ID_ATOR, NOME_ATOR) VALUES (SEQ_ATOR.NEXTVAL, 'WILL SMITH');
INSERT INTO ATOR (ID_ATOR, NOME_ATOR) VALUES (SEQ_ATOR.NEXTVAL, 'SCARLETT JOHANSSON');
INSERT INTO ATOR (ID_ATOR, NOME_ATOR) VALUES (SEQ_ATOR.NEXTVAL, 'KEANU REEVES');
INSERT INTO ATOR (ID_ATOR, NOME_ATOR) VALUES (SEQ_ATOR.NEXTVAL, 'ROBERT DOWNEY JR.');
INSERT INTO ATOR (ID_ATOR, NOME_ATOR) VALUES (SEQ_ATOR.NEXTVAL, 'DANIEL RADCLIFFE');
INSERT INTO ATOR (ID_ATOR, NOME_ATOR) VALUES (SEQ_ATOR.NEXTVAL, 'ANGELINA JOLIE');
INSERT INTO ATOR (ID_ATOR, NOME_ATOR) VALUES (SEQ_ATOR.NEXTVAL, 'CHRISTIAN BALE');
INSERT INTO ATOR (ID_ATOR, NOME_ATOR) VALUES (SEQ_ATOR.NEXTVAL, 'SAMUEL L. JACKSON');
INSERT INTO ATOR (ID_ATOR, NOME_ATOR) VALUES (SEQ_ATOR.NEXTVAL, 'LEONARDO DICAPRIO');
INSERT INTO ATOR (ID_ATOR, NOME_ATOR) VALUES (SEQ_ATOR.NEXTVAL, 'JENNIFER ANISTON');
INSERT INTO ATOR (ID_ATOR, NOME_ATOR) VALUES (SEQ_ATOR.NEXTVAL, 'HUGH JACKMAN');
INSERT INTO ATOR (ID_ATOR, NOME_ATOR) VALUES (SEQ_ATOR.NEXTVAL, 'JACKIE CHAN');
INSERT INTO ATOR (ID_ATOR, NOME_ATOR) VALUES (SEQ_ATOR.NEXTVAL, 'VIOLA DAVIS');
INSERT INTO ATOR (ID_ATOR, NOME_ATOR) VALUES (SEQ_ATOR.NEXTVAL, 'BEN AFFLECK');
  

INSERT INTO DIRETOR (ID_DIRETOR, NOME_DIR) VALUES (SEQ_DIRETOR.NEXTVAL, 'GEORGE LUCAS');
INSERT INTO DIRETOR (ID_DIRETOR, NOME_DIR) VALUES (SEQ_DIRETOR.NEXTVAL, 'STEVEN SPIELBERG');
INSERT INTO DIRETOR (ID_DIRETOR, NOME_DIR) VALUES (SEQ_DIRETOR.NEXTVAL, 'STANLEY KUBRICK');
INSERT INTO DIRETOR (ID_DIRETOR, NOME_DIR) VALUES (SEQ_DIRETOR.NEXTVAL, 'BERNARDO BERTOLUCCI');
INSERT INTO DIRETOR (ID_DIRETOR, NOME_DIR) VALUES (SEQ_DIRETOR.NEXTVAL, 'JEAN-LUC GODARD');
INSERT INTO DIRETOR (ID_DIRETOR, NOME_DIR) VALUES (SEQ_DIRETOR.NEXTVAL, 'QUENTIN TARANTINO');
INSERT INTO DIRETOR (ID_DIRETOR, NOME_DIR) VALUES (SEQ_DIRETOR.NEXTVAL, 'MARTIN SCORSESE');
INSERT INTO DIRETOR (ID_DIRETOR, NOME_DIR) VALUES (SEQ_DIRETOR.NEXTVAL, 'ALFRED HITCHCOCK');
INSERT INTO DIRETOR (ID_DIRETOR, NOME_DIR) VALUES (SEQ_DIRETOR.NEXTVAL, 'TIM BURTON');
INSERT INTO DIRETOR (ID_DIRETOR, NOME_DIR) VALUES (SEQ_DIRETOR.NEXTVAL, 'FRANCIS FORD COPPOLA');
INSERT INTO DIRETOR (ID_DIRETOR, NOME_DIR) VALUES (SEQ_DIRETOR.NEXTVAL, 'JAMES CAMERON');


INSERT INTO GENERO (ID_GENERO, DESCRICAO) VALUES (SEQ_GENERO.NEXTVAL, 'AÇÃO');
INSERT INTO GENERO (ID_GENERO, DESCRICAO) VALUES (SEQ_GENERO.NEXTVAL, 'ANIMAÇÃO');
INSERT INTO GENERO (ID_GENERO, DESCRICAO) VALUES (SEQ_GENERO.NEXTVAL, 'AVENTURA'); 
INSERT INTO GENERO (ID_GENERO, DESCRICAO) VALUES (SEQ_GENERO.NEXTVAL, 'COMÉDIA');
INSERT INTO GENERO (ID_GENERO, DESCRICAO) VALUES (SEQ_GENERO.NEXTVAL, 'COMÉDIA ROMÂNTICA'); 
INSERT INTO GENERO (ID_GENERO, DESCRICAO) VALUES (SEQ_GENERO.NEXTVAL, 'DOCUMENTÁRIOS'); 
INSERT INTO GENERO (ID_GENERO, DESCRICAO) VALUES (SEQ_GENERO.NEXTVAL, 'DRAMA'); 
INSERT INTO GENERO (ID_GENERO, DESCRICAO) VALUES (SEQ_GENERO.NEXTVAL, 'ESPIONAGEM'); 
INSERT INTO GENERO (ID_GENERO, DESCRICAO) VALUES (SEQ_GENERO.NEXTVAL, 'ERÓTICO');
INSERT INTO GENERO (ID_GENERO, DESCRICAO) VALUES (SEQ_GENERO.NEXTVAL, 'FANTASIA');
INSERT INTO GENERO (ID_GENERO, DESCRICAO) VALUES (SEQ_GENERO.NEXTVAL, 'FAROESTE');
INSERT INTO GENERO (ID_GENERO, DESCRICAO) VALUES (SEQ_GENERO.NEXTVAL, 'FICÇÃO CIENTÍFICA');
INSERT INTO GENERO (ID_GENERO, DESCRICAO) VALUES (SEQ_GENERO.NEXTVAL, 'GUERRA');
INSERT INTO GENERO (ID_GENERO, DESCRICAO) VALUES (SEQ_GENERO.NEXTVAL, 'MUSICAL');
INSERT INTO GENERO (ID_GENERO, DESCRICAO) VALUES (SEQ_GENERO.NEXTVAL, 'ROMANCE');
INSERT INTO GENERO (ID_GENERO, DESCRICAO) VALUES (SEQ_GENERO.NEXTVAL, 'SUSPENSE');
INSERT INTO GENERO (ID_GENERO, DESCRICAO) VALUES (SEQ_GENERO.NEXTVAL, 'TERROR'); 

INSERT INTO TEMPO (DIA, MES, ANO) VALUES (10,01,2023);
INSERT INTO TEMPO (DIA, MES, ANO) VALUES (10,02,2023);
INSERT INTO TEMPO (DIA, MES, ANO) VALUES (10,03,2023);
INSERT INTO TEMPO (DIA, MES, ANO) VALUES (10,04,2023);
INSERT INTO TEMPO (DIA, MES, ANO) VALUES (10,05,2023);
INSERT INTO TEMPO (DIA, MES, ANO) VALUES (10,06,2023);
INSERT INTO TEMPO (DIA, MES, ANO) VALUES (10,07,2023);
INSERT INTO TEMPO (DIA, MES, ANO) VALUES (10,07,2023);
INSERT INTO TEMPO (DIA, MES, ANO) VALUES (10,09,2023);
INSERT INTO TEMPO (DIA, MES, ANO) VALUES (10,10,2023);
INSERT INTO TEMPO (DIA, MES, ANO) VALUES (10,11,2023);
INSERT INTO TEMPO (DIA, MES, ANO) VALUES (10,12,2023);

INSERT INTO EXIBICAO (ID_CINEMA, ID_LOCAL, ID_ATOR, ID_DIRETOR, ID_GENERO, QUANTIDADE, VALOR) VALUES ( 1, 1, 14, 11, 1, 105, 958.35);
INSERT INTO EXIBICAO (ID_CINEMA, ID_LOCAL, ID_ATOR, ID_DIRETOR, ID_GENERO, QUANTIDADE, VALOR) VALUES ( 2, 2, 13, 10, 2, 200, 345.78);
INSERT INTO EXIBICAO (ID_CINEMA, ID_LOCAL, ID_ATOR, ID_DIRETOR, ID_GENERO, QUANTIDADE, VALOR) VALUES ( 3, 3, 12, 9, 3, 315, 258.58);
INSERT INTO EXIBICAO (ID_CINEMA, ID_LOCAL, ID_ATOR, ID_DIRETOR, ID_GENERO, QUANTIDADE, VALOR) VALUES ( 4, 4, 11, 8, 4, 412, 998.18);
INSERT INTO EXIBICAO (ID_CINEMA, ID_LOCAL, ID_ATOR, ID_DIRETOR, ID_GENERO, QUANTIDADE, VALOR) VALUES ( 5, 5, 10, 7, 5, 158, 858.23);
INSERT INTO EXIBICAO (ID_CINEMA, ID_LOCAL, ID_ATOR, ID_DIRETOR, ID_GENERO, QUANTIDADE, VALOR) VALUES ( 6, 6, 9, 6, 6, 997, 758.38);
INSERT INTO EXIBICAO (ID_CINEMA, ID_LOCAL, ID_ATOR, ID_DIRETOR, ID_GENERO, QUANTIDADE, VALOR) VALUES ( 7, 7, 8, 5, 7, 558, 658.15);
INSERT INTO EXIBICAO (ID_CINEMA, ID_LOCAL, ID_ATOR, ID_DIRETOR, ID_GENERO, QUANTIDADE, VALOR) VALUES ( 8, 8, 7, 4, 8, 679, 558.09);
INSERT INTO EXIBICAO (ID_CINEMA, ID_LOCAL, ID_ATOR, ID_DIRETOR, ID_GENERO, QUANTIDADE, VALOR) VALUES ( 9, 9, 6, 3, 9, 327, 358.95);
INSERT INTO EXIBICAO (ID_CINEMA, ID_LOCAL, ID_ATOR, ID_DIRETOR, ID_GENERO, QUANTIDADE, VALOR) VALUES ( 10, 10, 5, 2, 10, 667, 458.98);
INSERT INTO EXIBICAO (ID_CINEMA, ID_LOCAL, ID_ATOR, ID_DIRETOR, ID_GENERO, QUANTIDADE, VALOR) VALUES ( 1, 1, 4, 1, 11, 325, 158.97);
INSERT INTO EXIBICAO (ID_CINEMA, ID_LOCAL, ID_ATOR, ID_DIRETOR, ID_GENERO, QUANTIDADE, VALOR) VALUES ( 2, 2, 3, 11, 12, 131, 978.96);
INSERT INTO EXIBICAO (ID_CINEMA, ID_LOCAL, ID_ATOR, ID_DIRETOR, ID_GENERO, QUANTIDADE, VALOR) VALUES ( 3, 3, 2, 10, 13, 258, 988.78);
INSERT INTO EXIBICAO (ID_CINEMA, ID_LOCAL, ID_ATOR, ID_DIRETOR, ID_GENERO, QUANTIDADE, VALOR) VALUES ( 4, 4, 1,	9, 14, 123, 998.77);
INSERT INTO EXIBICAO (ID_CINEMA, ID_LOCAL, ID_ATOR, ID_DIRETOR, ID_GENERO, QUANTIDADE, VALOR) VALUES ( 5, 5, 1,8, 15, 189, 948.76);
INSERT INTO EXIBICAO (ID_CINEMA, ID_LOCAL, ID_ATOR, ID_DIRETOR, ID_GENERO, QUANTIDADE, VALOR) VALUES ( 6, 6, 2,	7, 16, 498, 938.75);
INSERT INTO EXIBICAO (ID_CINEMA, ID_LOCAL, ID_ATOR, ID_DIRETOR, ID_GENERO, QUANTIDADE, VALOR) VALUES ( 7, 7, 3, 6, 17, 175, 928.74);
INSERT INTO EXIBICAO (ID_CINEMA, ID_LOCAL, ID_ATOR, ID_DIRETOR, ID_GENERO, QUANTIDADE, VALOR) VALUES ( 8, 8, 4,	5, 1, 283, 918.73);
INSERT INTO EXIBICAO (ID_CINEMA, ID_LOCAL, ID_ATOR, ID_DIRETOR, ID_GENERO, QUANTIDADE, VALOR) VALUES ( 9, 9, 5,	4, 2, 198, 758.85);
INSERT INTO EXIBICAO (ID_CINEMA, ID_LOCAL, ID_ATOR, ID_DIRETOR, ID_GENERO, QUANTIDADE, VALOR) VALUES ( 10, 10, 6, 3, 3, 108, 658.88);
INSERT INTO EXIBICAO (ID_CINEMA, ID_LOCAL, ID_ATOR, ID_DIRETOR, ID_GENERO, QUANTIDADE, VALOR) VALUES ( 1, 1, 7, 2, 4, 277, 558.89);
INSERT INTO EXIBICAO (ID_CINEMA, ID_LOCAL, ID_ATOR, ID_DIRETOR, ID_GENERO, QUANTIDADE, VALOR) VALUES ( 2, 2, 8,	1, 5, 155, 458.82);
INSERT INTO EXIBICAO (ID_CINEMA, ID_LOCAL, ID_ATOR, ID_DIRETOR, ID_GENERO, QUANTIDADE, VALOR) VALUES ( 3, 3, 9, 1, 6, 245, 358.65);
INSERT INTO EXIBICAO (ID_CINEMA, ID_LOCAL, ID_ATOR, ID_DIRETOR, ID_GENERO, QUANTIDADE, VALOR) VALUES ( 4, 4, 10, 3,	7, 138, 258.66);
INSERT INTO EXIBICAO (ID_CINEMA, ID_LOCAL, ID_ATOR, ID_DIRETOR, ID_GENERO, QUANTIDADE, VALOR) VALUES ( 5, 5, 11, 5,	8, 433, 858.64);
INSERT INTO EXIBICAO (ID_CINEMA, ID_LOCAL, ID_ATOR, ID_DIRETOR, ID_GENERO, QUANTIDADE, VALOR) VALUES ( 6, 6, 12, 7, 9, 122, 589.63);
INSERT INTO EXIBICAO (ID_CINEMA, ID_LOCAL, ID_ATOR, ID_DIRETOR, ID_GENERO, QUANTIDADE, VALOR) VALUES ( 7, 7, 13, 9,	10, 517, 859.55);
INSERT INTO EXIBICAO (ID_CINEMA, ID_LOCAL, ID_ATOR, ID_DIRETOR, ID_GENERO, QUANTIDADE, VALOR) VALUES ( 8, 8, 14, 11, 11, 224, 758.54);
INSERT INTO EXIBICAO (ID_CINEMA, ID_LOCAL, ID_ATOR, ID_DIRETOR, ID_GENERO, QUANTIDADE, VALOR) VALUES ( 9, 9, 3,	2, 12, 116, 635.23);
INSERT INTO EXIBICAO (ID_CINEMA, ID_LOCAL, ID_ATOR, ID_DIRETOR, ID_GENERO, QUANTIDADE, VALOR) VALUES ( 10, 10, 4, 4, 13, 280, 512.82);
INSERT INTO EXIBICAO (ID_CINEMA, ID_LOCAL, ID_ATOR, ID_DIRETOR, ID_GENERO, QUANTIDADE, VALOR) VALUES ( 1, 1, 5,	6, 14, 182, 978.91);
INSERT INTO EXIBICAO (ID_CINEMA, ID_LOCAL, ID_ATOR, ID_DIRETOR, ID_GENERO, QUANTIDADE, VALOR) VALUES ( 2, 2, 6,	8, 15, 586, 999.99);
INSERT INTO EXIBICAO (ID_CINEMA, ID_LOCAL, ID_ATOR, ID_DIRETOR, ID_GENERO, QUANTIDADE, VALOR) VALUES ( 3, 3, 7, 10,	16, 618, 777.77);
INSERT INTO EXIBICAO (ID_CINEMA, ID_LOCAL, ID_ATOR, ID_DIRETOR, ID_GENERO, QUANTIDADE, VALOR) VALUES ( 4, 4, 8,	11,	17, 739, 666.05);



Os gerentes de área da distribuidora desejam acompanhar a evolução do público e o valor arrecadado na região do país, estado e cidade, classificados por GENERO de filme e cinema.

Também é necessário avaliar a evolução de filmes por ator participante, assim como por diretor.

Queremos saber quais os diretores que atraem maior público e em que GENEROs está esse público.

O tempo é fator fundamental de análise, pois precisamos ter a visão de quais períodos do ano possuem mais público por GENERO, ator e diretor, e geográficamente.