-- RESET
DROP TABLE RESERVA;
DROP TABLE SERVICO;
DROP TABLE DATA;
DROP TABLE MOTIVO_VIAGEM;
DROP TABLE MEIO_TRANSPORTE;
DROP TABLE APARTAMENTO;
DROP TABLE PROFISSAO;
DROP TABLE AGENCIA;
DROP TABLE TIPO_SERVICO;

DROP SEQUENCE SEQ_DATA;
DROP SEQUENCE SEQ_MOTIVO;
DROP SEQUENCE SEQ_TRANSPORTE;
DROP SEQUENCE SEQ_APARTAMENTO;
DROP SEQUENCE SEQ_PROFISSAO
DROP SEQUENCE SEQ_AGENCIA;
DROP SEQUENCE SEQ_TPSERVICO;

-- TABELAS DE DIMENSÃO "RESERVAS"
CREATE TABLE DATA (
  ID_DATA NUMBER(5) PRIMARY KEY,
  ANO NUMBER(4) NOT NULL,
  MES NUMBER(2) NOT NULL,
  TRIMESTRE NUMBER(1) NOT NULL
);

CREATE TABLE MOTIVO_VIAGEM (
  ID_MOTIVO NUMBER(5) PRIMARY KEY,
  DESCRICAO VARCHAR2(100) NOT NULL
);

CREATE TABLE MEIO_TRANSPORTE (
  ID_TRANSPORTE NUMBER(5) PRIMARY KEY,
  DESCRICAO VARCHAR2(100) NOT NULL
);

CREATE TABLE APARTAMENTO (
  ID_APARTAMENTO NUMBER(5) PRIMARY KEY,
  TIPO_APARTAMENTO VARCHAR2(100) NOT NULL
);

CREATE TABLE PROFISSAO (
  ID_PROFISSAO NUMBER(5) PRIMARY KEY,
  DESCRICAO VARCHAR2(100) NOT NULL
);

CREATE TABLE AGENCIA (
  ID_AGENCIA NUMBER(5) PRIMARY KEY,
  NOME VARCHAR2(100) NOT NULL
);

-- TABELA DE FATO "RESERVAS"
CREATE TABLE RESERVA (
    ID_DATA NUMBER(5) NOT NULL,
    ID_MOTIVO NUMBER(5) NOT NULL,
    ID_TRANSPORTE NUMBER(5) NOT NULL,
    ID_APARTAMENTO NUMBER(5) NOT NULL,
    ID_PROFISSAO NUMBER(5) NOT NULL,
    ID_AGENCIA NUMBER(5) NOT NULL,
    FATURAMENTO DECIMAL(10,2) NOT NULL,

    CONSTRAINT PK_RESERVA PRIMARY KEY (ID_DATA, ID_MOTIVO, ID_TRANSPORTE, ID_APARTAMENTO, ID_PROFISSAO, ID_AGENCIA), 
    CONSTRAINT FK_RESERVA_DATA FOREIGN KEY (ID_DATA) REFERENCES DATA (ID_DATA),
    CONSTRAINT FK_RESERVA_MOTIVO FOREIGN KEY (ID_MOTIVO) REFERENCES MOTIVO_VIAGEM (ID_MOTIVO),
    CONSTRAINT FK_RESERVA_TRANSPORTE FOREIGN KEY (ID_TRANSPORTE) REFERENCES MEIO_TRANSPORTE (ID_TRANSPORTE),
    CONSTRAINT FK_RESERVA_APARTAMENTO FOREIGN KEY (ID_APARTAMENTO) REFERENCES APARTAMENTO (ID_APARTAMENTO),
    CONSTRAINT FK_RESERVA_PROFISSAO FOREIGN KEY (ID_PROFISSAO) REFERENCES PROFISSAO (ID_PROFISSAO),
    CONSTRAINT FK_RESERVA_AGENCIA FOREIGN KEY (ID_AGENCIA) REFERENCES AGENCIA (ID_AGENCIA)
);

-- TABELAS DE DIMENSÃO "SERVICO"
CREATE TABLE TIPO_SERVICO (
    ID_TIPOSERVICO NUMBER(5) PRIMARY KEY,
    DESCRICAO VARCHAR2(100) NOT NULL
);

-- TABELAS DE FATO "SERVICO"
CREATE TABLE SERVICO (
  ID_DATA NUMBER(5) NOT NULL,
  ID_TIPOSERVICO NUMBER (5) NOT NULL,
  FATURAMENTO DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (ID_DATA, ID_TIPOSERVICO),
  CONSTRAINT FK_SERVICO_DATA FOREIGN KEY (ID_DATA) REFERENCES DATA (ID_DATA),
  CONSTRAINT FK_SERVICO_TIPO FOREIGN KEY (ID_TIPOSERVICO) REFERENCES TIPO_SERVICO (ID_TIPOSERVICO)
);

-- VARIÁVEIS DE INTERVALOS
CREATE SEQUENCE SEQ_DATA START WITH 1 INCREMENT BY 1 MAXVALUE 99999 NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_MOTIVO START WITH 1 INCREMENT BY 1 MAXVALUE 99999 NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_TRANSPORTE START WITH 1 INCREMENT BY 1 MAXVALUE 99999 NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_APARTAMENTO START WITH 1 INCREMENT BY 1 MAXVALUE 99999 NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_PROFISSAO START WITH 1 INCREMENT BY 1 MAXVALUE 99999 NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_AGENCIA START WITH 1 INCREMENT BY 1 MAXVALUE 99999 NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_TPSERVICO START WITH 1 INCREMENT BY 1 MAXVALUE 99999 NOCYCLE NOCACHE;

-- INSERINDO DADOS
INSERT INTO DATA (ID_DATA, ANO, MES, TRIMESTRE) VALUES (SEQ_DATA.NEXTVAL, 2022, 01, 1);
INSERT INTO DATA (ID_DATA, ANO, MES, TRIMESTRE) VALUES (SEQ_DATA.NEXTVAL, 2022, 05, 2);
INSERT INTO DATA (ID_DATA, ANO, MES, TRIMESTRE) VALUES (SEQ_DATA.NEXTVAL, 2022, 08, 3);
INSERT INTO DATA (ID_DATA, ANO, MES, TRIMESTRE) VALUES (SEQ_DATA.NEXTVAL, 2022, 12, 4);

INSERT INTO MOTIVO_VIAGEM (ID_MOTIVO, DESCRICAO) VALUES (SEQ_MOTIVO.NEXTVAL, 'Negocios');
INSERT INTO MOTIVO_VIAGEM (ID_MOTIVO, DESCRICAO) VALUES (SEQ_MOTIVO.NEXTVAL, 'Turismo');

INSERT INTO MEIO_TRANSPORTE (ID_TRANSPORTE, DESCRICAO) VALUES (SEQ_TRANSPORTE.NEXTVAL, 'Onibus');
INSERT INTO MEIO_TRANSPORTE (ID_TRANSPORTE, DESCRICAO) VALUES (SEQ_TRANSPORTE.NEXTVAL, 'Aviao');
INSERT INTO MEIO_TRANSPORTE (ID_TRANSPORTE, DESCRICAO) VALUES (SEQ_TRANSPORTE.NEXTVAL, 'Carro');

INSERT INTO APARTAMENTO (ID_APARTAMENTO, TIPO_APARTAMENTO) VALUES (SEQ_APARTAMENTO.NEXTVAL, 'Apartamento de um quarto');
INSERT INTO APARTAMENTO (ID_APARTAMENTO, TIPO_APARTAMENTO) VALUES (SEQ_APARTAMENTO.NEXTVAL, 'Apartamento de dois quartos');
INSERT INTO APARTAMENTO (ID_APARTAMENTO, TIPO_APARTAMENTO) VALUES (SEQ_APARTAMENTO.NEXTVAL, 'Apartamento de tres quarto');

INSERT INTO PROFISSAO (ID_PROFISSAO, DESCRICAO) VALUES (SEQ_PROFISSAO.NEXTVAL, 'Programador');
INSERT INTO PROFISSAO (ID_PROFISSAO, DESCRICAO) VALUES (SEQ_PROFISSAO.NEXTVAL, 'Professor');
INSERT INTO PROFISSAO (ID_PROFISSAO, DESCRICAO) VALUES (SEQ_PROFISSAO.NEXTVAL, 'Enfermeiro');

INSERT INTO AGENCIA (ID_AGENCIA, NOME) VALUES (SEQ_AGENCIA.NEXTVAL, 'Hostelworld');
INSERT INTO AGENCIA (ID_AGENCIA, NOME) VALUES (SEQ_AGENCIA.NEXTVAL, 'Agoda');
INSERT INTO AGENCIA (ID_AGENCIA, NOME) VALUES (SEQ_AGENCIA.NEXTVAL, 'Expedia');

INSERT INTO TIPO_SERVICO (ID_TIPOSERVICO, DESCRICAO) VALUES (SEQ_TPSERVICO.NEXTVAL, 'Bebidas');
INSERT INTO TIPO_SERVICO (ID_TIPOSERVICO, DESCRICAO) VALUES (SEQ_TPSERVICO.NEXTVAL, 'Alimentos');
INSERT INTO TIPO_SERVICO (ID_TIPOSERVICO, DESCRICAO) VALUES (SEQ_TPSERVICO.NEXTVAL, 'Frigobar');

INSERT INTO RESERVA (ID_DATA, ID_MOTIVO, ID_TRANSPORTE, ID_APARTAMENTO, ID_PROFISSAO, ID_AGENCIA, FATURAMENTO)
            VALUES (1,1,1,1,1,1,300.00);

INSERT INTO RESERVA (ID_DATA, ID_MOTIVO, ID_TRANSPORTE, ID_APARTAMENTO, ID_PROFISSAO, ID_AGENCIA, FATURAMENTO)
            VALUES (1,1,1,2,1,1,300.00);

INSERT INTO RESERVA (ID_DATA, ID_MOTIVO, ID_TRANSPORTE, ID_APARTAMENTO, ID_PROFISSAO, ID_AGENCIA, FATURAMENTO)
            VALUES (2,2,1,2,1,2,300.00);

INSERT INTO RESERVA (ID_DATA, ID_MOTIVO, ID_TRANSPORTE, ID_APARTAMENTO, ID_PROFISSAO, ID_AGENCIA, FATURAMENTO)
            VALUES (3,1,2,3,3,2,300.00);

INSERT INTO RESERVA (ID_DATA, ID_MOTIVO, ID_TRANSPORTE, ID_APARTAMENTO, ID_PROFISSAO, ID_AGENCIA, FATURAMENTO)
            VALUES (4,2,3,2,2,3,300.00);




-- SELECTS
-- Visualizar ao longo do tempo, com divisão por mês, o faturamento por motivo de viagem e meio de transporte.
SELECT DATA.MES"MES", MOTIVO_VIAGEM.DESCRICAO"MOTIVO DA VIAGEM", MEIO_TRANSPORTE.DESCRICAO"MEIO DE TRANSPORTE", SUM(RESERVA.FATURAMENTO) AS "FAT. TOTAL"
FROM RESERVA
JOIN DATA ON RESERVA.ID_DATA = DATA.ID_DATA
JOIN MOTIVO_VIAGEM ON RESERVA.ID_MOTIVO = MOTIVO_VIAGEM.ID_MOTIVO
JOIN MEIO_TRANSPORTE ON RESERVA.ID_TRANSPORTE = MEIO_TRANSPORTE.ID_TRANSPORTE
GROUP BY CUBE(DATA.MES, MOTIVO_VIAGEM.DESCRICAO, MEIO_TRANSPORTE.DESCRICAO);

-- Evolução do faturamento por tipo de apartamento por trimestre.
SELECT DATA.TRIMESTRE,APARTAMENTO.TIPO_APARTAMENTO"TIPO DO APARTAMENTO", SUM(RESERVA.FATURAMENTO) AS "FAT. TOTAL"
FROM RESERVA
JOIN DATA ON RESERVA.ID_DATA = DATA.ID_DATA
JOIN APARTAMENTO ON RESERVA.ID_APARTAMENTO = APARTAMENTO.ID_APARTAMENTO
GROUP BY CUBE(DATA.TRIMESTRE,APARTAMENTO.TIPO_APARTAMENTO);

-- Faturamento de serviços com consumo de bebidas e alimentos em reais por tipo de serviço.
SELECT TIPO_SERVICO.DESCRICAO"TIPO DE SERVICO", SUM(SERVICO.FATURAMENTO) AS "FAT. TOTAL"
FROM SERVICO
JOIN TIPO_SERVICO ON SERVICO.ID_TIPOSERVICO = TIPO_SERVICO.ID_TIPOSERVICO
WHERE TIPO_SERVICO.DESCRICAO IN ('Bebidas', 'Alimentos')
GROUP BY TIPO_SERVICO.DESCRICAO;

-- Faturamento por profissão de hóspede.
SELECT PROFISSAO.DESCRICAO"PROFISSAO", SUM(RESERVA.FATURAMENTO) AS "FAT. TOTAL"
FROM RESERVA
JOIN PROFISSAO ON RESERVA.ID_PROFISSAO = PROFISSAO.ID_PROFISSAO
GROUP BY PROFISSAO.DESCRICAO;

-- Faturamento por agências.
SELECT AGENCIA.NOME, SUM(RESERVA.FATURAMENTO)
FROM RESERVA
JOIN AGENCIA ON RESERVA.ID_AGENCIA = AGENCIA.ID_AGENCIA
GROUP BY AGENCIA.NOME;

-- Faturamento por viagem de negócios, distribuído em diárias e consumos de frigobar.
-- SELECT DATA.mes, 
--        SUM(RESERVA.diarias * dim_tipos_apartamento.valor_diaria) AS faturamento_diarias,
--        SUM(RESERVA.consumo_frigobar) AS faturamento_frigobar,
--        SUM(RESERVA.faturamento) AS faturamento_total
-- FROM RESERVA
-- JOIN DATA ON RESERVA.data_id = DATA.id
-- JOIN MOTIVO_VIAGEM ON RESERVA.motivo_viagem_id = MOTIVO_VIAGEM.id
-- JOIN MEIO_TRANSPORTE ON RESERVA.meio_transporte_id = MEIO_TRANSPORTE.id
-- JOIN dim_tipos_apartamento ON RESERVA.tipo_apartamento_id = dim_tipos_apartamento.id
-- WHERE MOTIVO_VIAGEM.DESCRICAO = 'Negocios'
-- GROUP BY DATA.mes;