/*

CREATE TABLE QUESTION (
    ID_QUES INT(3) PRIMARY KEY AUTO_INCREMENT,
    QUESTION VARCHAR(255) NOT NULL,
    DISCIPLINE VARCHAR(100) NOT NULL
);

CREATE TABLE ANSWER (
    ID_ANS INT(3) PRIMARY KEY AUTO_INCREMENT,
    ANSWER TEXT(800) NOT NULL,
    CORRECT ENUM('X','x', '') NOT NULL,
    ID_QUES INT(3) NOT NULL,

    CONSTRAINT FK_ANS_QUEST FOREIGN KEY(ID_QUES) REFERENCES QUESTION(ID_QUES)

);