-- Drops table and sequences
DROP TABLE T_BANCA;
DROP TABLE T_GRUPO;
DROP TABLE T_ALUNO;
DROP TABLE T_TCC;
DROP TABLE T_CURSO;
DROP TABLE T_PROFESSOR;
DROP SEQUENCE SEQ_PROFESSOR;
DROP SEQUENCE SEQ_ALUNO;
DROP SEQUENCE SEQ_CURSO;
DROP SEQUENCE SEQ_TCC;

-- Create tables
CREATE TABLE T_PROFESSOR (
ID_PROFESSOR NUMBER(5) PRIMARY KEY,
NOME VARCHAR2(120) NOT NULL,
ATIVO CHAR(1) NOT NULL,
CONSTRAINT CK_ATIVO_PROFESSOR CHECK (ATIVO IN ('S', 'N'))
);

CREATE TABLE T_CURSO (
ID_CURSO NUMBER(5) PRIMARY KEY,
NOME VARCHAR2(40) NOT NULL,
ATIVO CHAR(1) NOT NULL,
CONSTRAINT CK_ATIVO_CURSO CHECK (ATIVO IN ('S', 'N')),
CONSTRAINT UQ_CURSO_NOME UNIQUE(NOME)
);

CREATE TABLE T_ALUNO (
ID_ALUNO NUMBER(5) PRIMARY KEY,
NUM_REGISTRO NUMBER(12) NOT NULL,
NOME VARCHAR2(120) NOT NULL,
ANO_SEMESTRE_INICIO CHAR(8) NOT NULL,
ANO_SEMESTRE_FIM CHAR(8) NULL,
ATIVO CHAR(1) NOT NULL,
CONSTRAINT CK_ATIVO_ALUNO CHECK (ATIVO IN ('S', 'N')),
CONSTRAINT UQ_REGISTRO UNIQUE (NUM_REGISTRO)
);

CREATE TABLE T_TCC (
ID_TCC NUMBER(5) PRIMARY KEY,
ID_ORIENTADOR NUMBER(5),
TITULO VARCHAR2(100) NOT NULL,
RESUMO VARCHAR2(255) NOT NULL,
QNT_PAGINAS NUMBER(3) NOT NULL,
PALAVRAS_CHAVE VARCHAR2(80) NOT NULL,
NOME_ARQUIVO VARCHAR2(400) NOT NULL,
DATAHORA_INICIO TIMESTAMP NOT NULL,
ATIVO CHAR(1) NOT NULL,
CONSTRAINT CK_ATIVO_TCC CHECK (ATIVO IN ('S', 'N')),
FOREIGN KEY(ID_ORIENTADOR) REFERENCES T_PROFESSOR (ID_PROFESSOR)
);

-- Create link tables
CREATE TABLE T_BANCA (
ID_PROFESSOR NUMBER(5),
ID_TCC NUMBER(5),
ATIVO CHAR(1) NOT NULL,
CONSTRAINT CK_ATIVO_BANCA CHECK (ATIVO IN ('S', 'N')),
PRIMARY KEY (ID_PROFESSOR, ID_TCC),
FOREIGN KEY(ID_PROFESSOR) REFERENCES T_PROFESSOR (ID_PROFESSOR),
FOREIGN KEY(ID_TCC) REFERENCES T_TCC (ID_TCC)
);

CREATE TABLE T_GRUPO (
ID_ALUNO NUMBER(5),
ID_TCC NUMBER(5),
ATIVO CHAR(1) NOT NULL,
CONSTRAINT CK_ATIVO_GRUPO CHECK (ATIVO IN ('S', 'N')),
PRIMARY KEY (ID_ALUNO, ID_TCC),
FOREIGN KEY(ID_ALUNO) REFERENCES T_ALUNO (ID_ALUNO),
FOREIGN KEY(ID_TCC) REFERENCES T_TCC (ID_TCC)
);

-- Create sequences
CREATE SEQUENCE SEQ_PROFESSOR START WITH 1 INCREMENT BY 1 MAXVALUE 99999 NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_CURSO START WITH 1 INCREMENT BY 1 MAXVALUE 99999 NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_ALUNO START WITH 1 INCREMENT BY 1 MAXVALUE 99999 NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_TCC START WITH 1 INCREMENT BY 1 MAXVALUE 99999 NOCYCLE NOCACHE;

-- Insert values
INSERT INTO T_PROFESSOR (ID_PROFESSOR, NOME, ATIVO) VALUES (SEQ_PROFESSOR.NEXTVAL, 'Luis Alexandre da Silva', 'S');
INSERT INTO T_PROFESSOR (ID_PROFESSOR, NOME, ATIVO) VALUES (SEQ_PROFESSOR.NEXTVAL, 'Kleber Luis Nardoto Milaneze', 'S');
INSERT INTO T_PROFESSOR (ID_PROFESSOR, NOME, ATIVO) VALUES (SEQ_PROFESSOR.NEXTVAL, 'Camila Maria da Costa Kami', 'S');
INSERT INTO T_PROFESSOR (ID_PROFESSOR, NOME, ATIVO) VALUES (SEQ_PROFESSOR.NEXTVAL, 'Rogeria Maria Alves de Almeida', 'S');
INSERT INTO T_PROFESSOR (ID_PROFESSOR, NOME, ATIVO) VALUES (SEQ_PROFESSOR.NEXTVAL, 'Patrícia Bellin Ribeiro', 'S');
INSERT INTO T_PROFESSOR (ID_PROFESSOR, NOME, ATIVO) VALUES (SEQ_PROFESSOR.NEXTVAL, 'Gustavo Cesar Bruschi', 'S');
INSERT INTO T_PROFESSOR (ID_PROFESSOR, NOME, ATIVO) VALUES (SEQ_PROFESSOR.NEXTVAL, 'Marcos Danilo Graciano', 'S');

INSERT INTO T_CURSO (ID_CURSO, NOME, ATIVO) VALUES (SEQ_CURSO.NEXTVAL, 'Banco de Dados', 'S');
INSERT INTO T_CURSO (ID_CURSO, NOME, ATIVO) VALUES (SEQ_CURSO.NEXTVAL, 'Sistema Biomédicos', 'S');
INSERT INTO T_CURSO (ID_CURSO, NOME, ATIVO) VALUES (SEQ_CURSO.NEXTVAL, 'Automacão Industrial', 'S');
INSERT INTO T_CURSO (ID_CURSO, NOME, ATIVO) VALUES (SEQ_CURSO.NEXTVAL, 'Rede de Computadores', 'S');

INSERT INTO T_ALUNO (ID_ALUNO, NUM_REGISTRO, NOME, ANO_SEMESTRE_INICIO, ANO_SEMESTRE_FIM, ATIVO)
    VALUES (SEQ_ALUNO.NEXTVAL, 000000000001, 'Adrian Colombo', '202001', '202202', 'N');
INSERT INTO T_ALUNO (ID_ALUNO, NUM_REGISTRO, NOME, ANO_SEMESTRE_INICIO, ANO_SEMESTRE_FIM, ATIVO)
    VALUES (SEQ_ALUNO.NEXTVAL, 000000000002, 'Rafael Oliveira', '202001', '202202', 'N');
INSERT INTO T_ALUNO (ID_ALUNO, NUM_REGISTRO, NOME, ANO_SEMESTRE_INICIO, ANO_SEMESTRE_FIM, ATIVO)
    VALUES (SEQ_ALUNO.NEXTVAL, 000000000003, 'Gabriele Rocha', '202002', '202301', 'S');
INSERT INTO T_ALUNO (ID_ALUNO, NUM_REGISTRO, NOME, ANO_SEMESTRE_INICIO, ANO_SEMESTRE_FIM, ATIVO)
    VALUES (SEQ_ALUNO.NEXTVAL, 000000000004, 'Isabele Santos', '202101', '', 'S');
INSERT INTO T_ALUNO (ID_ALUNO, NUM_REGISTRO, NOME, ANO_SEMESTRE_INICIO, ANO_SEMESTRE_FIM, ATIVO)
    VALUES (SEQ_ALUNO.NEXTVAL, 000000000005, 'Laura Silvia', '202101', '', 'S');
INSERT INTO T_ALUNO (ID_ALUNO, NUM_REGISTRO, NOME, ANO_SEMESTRE_INICIO, ANO_SEMESTRE_FIM, ATIVO)
    VALUES (SEQ_ALUNO.NEXTVAL, 000000000006, 'Ricardo Leme', '202101', '', 'S');

INSERT INTO T_TCC (ID_TCC, ID_ORIENTADOR, TITULO, RESUMO, QNT_PAGINAS, PALAVRAS_CHAVE, NOME_ARQUIVO, DATAHORA_INICIO, ATIVO)
    VALUES (SEQ_TCC.NEXTVAL, 1, 'Análise do impacto ambiental das atividades econômicas na região metropolitana', 'Este trabalho tem como objetivo avaliar o impacto ambiental das atividades econômicas na região metropolitana, com foco em três setores: indústria, transporte e turismo.', 60, 'Meio ambiente, sustentabilidade, poluição, desenvolvimento econômico', 'tcc_impacto_ambiental.pdf', TO_DATE('20/11/2022 20:30:00', 'DD/MM/YYYY HH24:MI:SS'), 'N');

INSERT INTO T_TCC (ID_TCC, ID_ORIENTADOR, TITULO, RESUMO, QNT_PAGINAS, PALAVRAS_CHAVE, NOME_ARQUIVO, DATAHORA_INICIO, ATIVO)
    VALUES (SEQ_TCC.NEXTVAL, 2, 'Impactos da Transformação Digital nas Empresas Brasileiras', 'Este trabalho tem como objetivo analisar os impactos da transformação digital nas empresas brasileiras, com foco nos setores de varejo, serviços financeiros e manufatura.', 80, 'Transformação Digital, Inovação, Competitividade, Automação', 'tcc_transformacao_digital.pdf', TO_DATE('15/05/2022 10:00:00', 'DD/MM/YYYY HH24:MI:SS'), 'N');

INSERT INTO T_BANCA (ID_TCC, ID_PROFESSOR) VALUES (1,2);
INSERT INTO T_BANCA (ID_TCC, ID_PROFESSOR) VALUES (1,3);
INSERT INTO T_BANCA (ID_TCC, ID_PROFESSOR) VALUES (1,1);

INSERT INTO T_BANCA (ID_TCC, ID_PROFESSOR) VALUES (2,2);
INSERT INTO T_BANCA (ID_TCC, ID_PROFESSOR) VALUES (2,3);
INSERT INTO T_BANCA (ID_TCC, ID_PROFESSOR) VALUES (2,4);

INSERT INTO T_GRUPO (ID_TCC, ID_ALUNO) VALUES (1,1);
INSERT INTO T_GRUPO (ID_TCC, ID_ALUNO) VALUES (1,2);
INSERT INTO T_GRUPO (ID_TCC, ID_ALUNO) VALUES (1,3);

INSERT INTO T_GRUPO (ID_TCC, ID_ALUNO) VALUES (2,4);
INSERT INTO T_GRUPO (ID_TCC, ID_ALUNO) VALUES (2,5);
INSERT INTO T_GRUPO (ID_TCC, ID_ALUNO) VALUES (2,6);

SELECT TCC.TITULO "TÍTULO",
       ALUNOS.INTEGRANTES,
       ORIENTADOR.NOME "ORIENTADOR",
       LISTAGG(DISTINCT PROFESSOR.NOME, ', ') WITHIN GROUP (ORDER BY PROFESSOR.NOME) "BANCA"
FROM T_TCC TCC
JOIN T_GRUPO GRUPO ON TCC.ID_TCC = GRUPO.ID_TCC
JOIN (
  SELECT GRUPO.ID_TCC,
         LISTAGG(ALUNO.NOME, ', ') WITHIN GROUP (ORDER BY ALUNO.NOME) AS "INTEGRANTES"
  FROM T_GRUPO GRUPO
  JOIN T_ALUNO ALUNO ON GRUPO.ID_ALUNO = ALUNO.ID_ALUNO
  -- WHERE GRUPO.ID_TCC = 1
  GROUP BY GRUPO.ID_TCC
) ALUNOS ON TCC.ID_TCC = ALUNOS.ID_TCC
JOIN T_BANCA BANCA ON TCC.ID_TCC = BANCA.ID_TCC
JOIN T_PROFESSOR PROFESSOR ON BANCA.ID_PROFESSOR = PROFESSOR.ID_PROFESSOR
JOIN T_PROFESSOR ORIENTADOR ON TCC.ID_ORIENTADOR = ORIENTADOR.ID_PROFESSOR
-- WHERE GRUPO.ID_TCC = 1
GROUP BY TCC.TITULO, ALUNOS.INTEGRANTES, ORIENTADOR.NOME;


-------------------------------- PARTE 2 ---------------------------------------------
---------------------------- Função/TAB LOG ------------------------------------------
-- Tabela de LOG
CREATE TABLE LOG_CADASTRO_CURSO(
    ID_LOG NUMBER PRIMARY KEY,
    NOMEPROG VARCHAR2(30) NOT NULL,
    PARAMENTRADA VARCHAR2(120) NULL,
    CODERRO NUMBER(6) NOT NULL,
    DESCERRO VARCHAR2(500) NOT NULL,
    LINHAERRO VARCHAR2(500) NOT NULL,
    USUARIO VARCHAR2(30) NOT NULL,
    DATAHORA DATE NOT NULL,
    STATUS CHAR(1) NOT NULL, -- E-ERRO / S-SUCESSO
    NOTA VARCHAR2(500) NULL
);

CREATE SEQUENCE SEQ_LOG NOCACHE NOCYCLE;

-- Função
CREATE OR REPLACE FUNCTION FUNC_CADASTRA_CURSO(
    P_ID_CURSO IN T_CURSO.ID_CURSO%TYPE,
    P_NOME IN T_CURSO.NOME%TYPE,
    P_ATIVO IN T_CURSO.ATIVO%TYPE
)

RETURN NUMBER
IS
V_STATUS CHAR(1);
V_COUNT NUMBER;
P_RETORNO NUMBER(5);
V_ERRO NUMBER;
V_DESCERRO VARCHAR2(500);

BEGIN
-- Verifica se o ID do curso já existe na tabela
SELECT COUNT(*)
INTO V_COUNT
FROM T_CURSO
WHERE ID_CURSO = P_ID_CURSO;

IF V_COUNT > 0 THEN
    P_RETORNO := -999;
    V_STATUS := 'E';
    V_DESCERRO := 'ID do curso já existente na tabela';
ELSE
    -- Verifica se o nome do curso já existe na tabela
    SELECT COUNT(*)
    INTO V_COUNT
    FROM T_CURSO
    WHERE UPPER(NOME) = UPPER(P_NOME);

    IF V_COUNT > 0 THEN
        P_RETORNO := -998;
        V_STATUS := 'E';
        V_DESCERRO := 'Nome do curso já existente na tabela';
    ELSE

        -- Insere o curso na tabela
        INSERT INTO T_CURSO (ID_CURSO, NOME, ATIVO) VALUES (P_ID_CURSO, P_NOME, P_ATIVO);
        P_RETORNO := 0;
        V_STATUS := 'S';
        V_DESCERRO := 'Inserido com sucesso';
    END IF;
END IF;

INSERT INTO LOG_CADASTRO_CURSO ( ID_LOG, NOMEPROG, PARAMENTRADA, CODERRO, DESCERRO, LINHAERRO, USUARIO, DATAHORA, STATUS, NOTA)
    VALUES (
    SEQ_LOG.NEXTVAL,
    'FUNC_LOG_CADASTRO_CURSO',
    'P_ID_CURSO = ' || P_ID_CURSO || 'P_NOME = ' || P_NOME || 'P_ATIVO = ' || P_ATIVO,
    P_RETORNO,
    V_DESCERRO,
    '--',
    USER,
    SYSDATE,
    V_STATUS,
    NULL
    );

COMMIT;
RETURN P_RETORNO;

EXCEPTION
WHEN OTHERS THEN
V_ERRO := SQLCODE;
V_DESCERRO := SQLERRM;
V_STATUS := 'E';
INSERT INTO LOG_CADASTRO_CURSO ( ID_LOG, NOMEPROG, PARAMENTRADA, CODERRO, DESCERRO, LINHAERRO, USUARIO, DATAHORA, STATUS, NOTA)
    VALUES (
    SEQ_LOG.NEXTVAL,
    'FUNC_LOG_CADASTRO_CURSO',
    'P_ID_CURSO = ' || P_ID_CURSO || 'P_NOME = ' || P_NOME || 'P_ATIVO = ' || P_ATIVO,
    V_ERRO,
    V_DESCERRO,
    DBMS_UTILITY.FORMAT_ERROR_BACKTRACE(),
    USER,
    SYSDATE,
    V_STATUS,
    NULL
    );
COMMIT;
RETURN P_RETORNO;

END;

-- Execução
DECLARE
    P_ID_CURSO T_CURSO.ID_CURSO%TYPE := 1;
    P_NOME T_CURSO.NOME%TYPE := 'XXXX';
    P_ATIVO T_CURSO.ATIVO%TYPE := 'S';
    P_RETORNO NUMBER;

BEGIN
    P_RETORNO := FUNC_CADASTRA_CURSO(P_ID_CURSO, P_NOME, P_ATIVO);
    DBMS_OUTPUT.PUT_LINE('COD: ' || P_RETORNO);

END;
