-- Drops table and sequences
DROP TABLE T_BANCA;
DROP TABLE T_GRUPO;
DROP TABLE T_ALUNO;
DROP TABLE T_TCC;
DROP TABLE T_CURSO;
DROP TABLE T_PROFESSOR;
DROP SEQUENCE SEQ_PROFESSOR;
DROP SEQUENCE SEQ_ALUNO;
DROP SEQUENCE SEQ_CURSO;
DROP SEQUENCE SEQ_TCC;

-- Create tables
CREATE TABLE T_PROFESSOR (
ID_PROFESSOR NUMBER(5) PRIMARY KEY,
NOME VARCHAR2(120) NOT NULL,
ATIVO CHAR(1) NOT NULL,
CONSTRAINT CK_ATIVO_PROFESSOR CHECK (ATIVO IN ('S', 'N'))
);

CREATE TABLE T_CURSO (
ID_CURSO NUMBER(5) PRIMARY KEY,
NOME VARCHAR2(40) NOT NULL,
ATIVO CHAR(1) NOT NULL,
CONSTRAINT CK_ATIVO_CURSO CHECK (ATIVO IN ('S', 'N')),
CONSTRAINT UQ_CURSO_NOME UNIQUE(NOME)
);

CREATE TABLE T_ALUNO (
ID_ALUNO NUMBER(5) PRIMARY KEY,
NUM_REGISTRO NUMBER(12) NOT NULL,
NOME VARCHAR2(120) NOT NULL,
ANO_SEMESTRE_INICIO CHAR(8) NOT NULL,
ANO_SEMESTRE_FIM CHAR(8) NULL,
ATIVO CHAR(1) NOT NULL,
CONSTRAINT CK_ATIVO_ALUNO CHECK (ATIVO IN ('S', 'N')),
CONSTRAINT UQ_REGISTRO UNIQUE (NUM_REGISTRO)
);

CREATE TABLE T_TCC (
ID_TCC NUMBER(5) PRIMARY KEY,
ID_ORIENTADOR NUMBER(5),
TITULO VARCHAR2(100) NOT NULL,
RESUMO VARCHAR2(255) NOT NULL,
QNT_PAGINAS NUMBER(3) NOT NULL,
PALAVRAS_CHAVE VARCHAR2(80) NOT NULL,
NOME_ARQUIVO VARCHAR2(400) NOT NULL,
DATAHORA_INICIO TIMESTAMP NOT NULL,
ATIVO CHAR(1) NOT NULL,
CONSTRAINT CK_ATIVO_TCC CHECK (ATIVO IN ('S', 'N')),
FOREIGN KEY(ID_ORIENTADOR) REFERENCES T_PROFESSOR (ID_PROFESSOR)
);

-- Create link tables
CREATE TABLE T_BANCA (
ID_PROFESSOR NUMBER(5),
ID_TCC NUMBER(5),
ATIVO CHAR(1) NOT NULL,
CONSTRAINT CK_ATIVO_TCC CHECK (ATIVO IN ('S', 'N')),
PRIMARY KEY (ID_PROFESSOR, ID_TCC),
FOREIGN KEY(ID_PROFESSOR) REFERENCES T_PROFESSOR (ID_PROFESSOR),
FOREIGN KEY(ID_TCC) REFERENCES T_TCC (ID_TCC)
);

CREATE TABLE T_GRUPO (
ID_ALUNO NUMBER(5),
ID_TCC NUMBER(5),
ATIVO CHAR(1) NOT NULL,
CONSTRAINT CK_ATIVO_TCC CHECK (ATIVO IN ('S', 'N')),
PRIMARY KEY (ID_ALUNO, ID_TCC),
FOREIGN KEY(ID_ALUNO) REFERENCES T_ALUNO (ID_ALUNO),
FOREIGN KEY(ID_TCC) REFERENCES T_TCC (ID_TCC)
);

-- Create sequences
CREATE SEQUENCE SEQ_PROFESSOR START WITH 1 INCREMENT BY 1 MAXVALUE 99999 NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_CURSO START WITH 1 INCREMENT BY 1 MAXVALUE 99999 NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_ALUNO START WITH 1 INCREMENT BY 1 MAXVALUE 99999 NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_TCC START WITH 1 INCREMENT BY 1 MAXVALUE 99999 NOCYCLE NOCACHE;

-- Insert values
INSERT INTO T_PROFESSOR (ID_PROFESSOR, NOME, ATIVO) VALUES (SEQ_PROFESSOR.NEXTVAL, 'Luis Alexandre da Silva', 'S');
INSERT INTO T_PROFESSOR (ID_PROFESSOR, NOME, ATIVO) VALUES (SEQ_PROFESSOR.NEXTVAL, 'Kleber Luis Nardoto Milaneze', 'S');
INSERT INTO T_PROFESSOR (ID_PROFESSOR, NOME, ATIVO) VALUES (SEQ_PROFESSOR.NEXTVAL, 'Camila Maria da Costa Kami', 'S');
INSERT INTO T_PROFESSOR (ID_PROFESSOR, NOME, ATIVO) VALUES (SEQ_PROFESSOR.NEXTVAL, 'Rogeria Maria Alves de Almeida', 'S');
INSERT INTO T_PROFESSOR (ID_PROFESSOR, NOME, ATIVO) VALUES (SEQ_PROFESSOR.NEXTVAL, 'Patrícia Bellin Ribeiro', 'S');
INSERT INTO T_PROFESSOR (ID_PROFESSOR, NOME, ATIVO) VALUES (SEQ_PROFESSOR.NEXTVAL, 'Gustavo Cesar Bruschi', 'S');
INSERT INTO T_PROFESSOR (ID_PROFESSOR, NOME, ATIVO) VALUES (SEQ_PROFESSOR.NEXTVAL, 'Marcos Danilo Graciano', 'S');

INSERT INTO T_CURSO (ID_CURSO, NOME, ATIVO) VALUES (SEQ_CURSO.NEXTVAL, 'Banco de Dados', 'S');
INSERT INTO T_CURSO (ID_CURSO, NOME, ATIVO) VALUES (SEQ_CURSO.NEXTVAL, 'Sistema Biomédicos', 'S');
INSERT INTO T_CURSO (ID_CURSO, NOME, ATIVO) VALUES (SEQ_CURSO.NEXTVAL, 'Automacão Industrial', 'S');
INSERT INTO T_CURSO (ID_CURSO, NOME, ATIVO) VALUES (SEQ_CURSO.NEXTVAL, 'Rede de Computadores', 'S');

INSERT INTO T_ALUNO (ID_ALUNO, NUM_REGISTRO, NOME, ANO_SEMESTRE_INICIO, ANO_SEMESTRE_FIM, ATIVO)
    VALUES (SEQ_ALUNO.NEXTVAL, 000000000001, 'Adrian Colombo', '202001', '202202', 'N');
INSERT INTO T_ALUNO (ID_ALUNO, NUM_REGISTRO, NOME, ANO_SEMESTRE_INICIO, ANO_SEMESTRE_FIM, ATIVO)
    VALUES (SEQ_ALUNO.NEXTVAL, 000000000002, 'Rafael Oliveira', '202001', '202202', 'N');
INSERT INTO T_ALUNO (ID_ALUNO, NUM_REGISTRO, NOME, ANO_SEMESTRE_INICIO, ANO_SEMESTRE_FIM, ATIVO)
    VALUES (SEQ_ALUNO.NEXTVAL, 000000000003, 'Gabriele Rocha', '202002', '202301', 'S');
INSERT INTO T_ALUNO (ID_ALUNO, NUM_REGISTRO, NOME, ANO_SEMESTRE_INICIO, ANO_SEMESTRE_FIM, ATIVO)
    VALUES (SEQ_ALUNO.NEXTVAL, 000000000004, 'Isabele Santos', '202101', '', 'S');
INSERT INTO T_ALUNO (ID_ALUNO, NUM_REGISTRO, NOME, ANO_SEMESTRE_INICIO, ANO_SEMESTRE_FIM, ATIVO)
    VALUES (SEQ_ALUNO.NEXTVAL, 000000000005, 'Laura Silvia', '202101', '', 'S');
INSERT INTO T_ALUNO (ID_ALUNO, NUM_REGISTRO, NOME, ANO_SEMESTRE_INICIO, ANO_SEMESTRE_FIM, ATIVO)
    VALUES (SEQ_ALUNO.NEXTVAL, 000000000006, 'Ricardo Leme', '202101', '', 'S');

INSERT INTO T_TCC (ID_TCC, ID_ORIENTADOR, TITULO, RESUMO, QNT_PAGINAS, PALAVRAS_CHAVE, NOME_ARQUIVO, DATAHORA_INICIO, ATIVO)
    VALUES (SEQ_TCC.NEXTVAL, 1, 'Análise do impacto ambiental das atividades econômicas na região metropolitana', 'Este trabalho tem como objetivo avaliar o impacto ambiental das atividades econômicas na região metropolitana, com foco em três setores: indústria, transporte e turismo.', 60, 'Meio ambiente, sustentabilidade, poluição, desenvolvimento econômico', 'tcc_impacto_ambiental.pdf', TO_DATE('20/11/2022 20:30:00', 'DD/MM/YYYY HH24:MI:SS'), 'N');

INSERT INTO T_TCC (ID_TCC, ID_ORIENTADOR, TITULO, RESUMO, QNT_PAGINAS, PALAVRAS_CHAVE, NOME_ARQUIVO, DATAHORA_INICIO, ATIVO)
    VALUES (SEQ_TCC.NEXTVAL, 2, 'Impactos da Transformação Digital nas Empresas Brasileiras', 'Este trabalho tem como objetivo analisar os impactos da transformação digital nas empresas brasileiras, com foco nos setores de varejo, serviços financeiros e manufatura.', 80, 'Transformação Digital, Inovação, Competitividade, Automação', 'tcc_transformacao_digital.pdf', TO_DATE('15/05/2022 10:00:00', 'DD/MM/YYYY HH24:MI:SS'), 'N');

INSERT INTO T_BANCA (ID_TCC, ID_PROFESSOR) VALUES (1,2);
INSERT INTO T_BANCA (ID_TCC, ID_PROFESSOR) VALUES (1,3);
INSERT INTO T_BANCA (ID_TCC, ID_PROFESSOR) VALUES (1,1);

INSERT INTO T_BANCA (ID_TCC, ID_PROFESSOR) VALUES (2,2);
INSERT INTO T_BANCA (ID_TCC, ID_PROFESSOR) VALUES (2,3);
INSERT INTO T_BANCA (ID_TCC, ID_PROFESSOR) VALUES (2,4);

INSERT INTO T_GRUPO (ID_TCC, ID_ALUNO) VALUES (1,1);
INSERT INTO T_GRUPO (ID_TCC, ID_ALUNO) VALUES (1,2);
INSERT INTO T_GRUPO (ID_TCC, ID_ALUNO) VALUES (1,3);

INSERT INTO T_GRUPO (ID_TCC, ID_ALUNO) VALUES (2,4);
INSERT INTO T_GRUPO (ID_TCC, ID_ALUNO) VALUES (2,5);
INSERT INTO T_GRUPO (ID_TCC, ID_ALUNO) VALUES (2,6);

SELECT TCC.TITULO "TÍTULO",
       ALUNOS.INTEGRANTES,
       ORIENTADOR.NOME "ORIENTADOR",
       LISTAGG(DISTINCT PROFESSOR.NOME, ', ') WITHIN GROUP (ORDER BY PROFESSOR.NOME) "BANCA"
FROM T_TCC TCC
JOIN T_GRUPO GRUPO ON TCC.ID_TCC = GRUPO.ID_TCC
JOIN (
  SELECT GRUPO.ID_TCC,
         LISTAGG(ALUNO.NOME, ', ') WITHIN GROUP (ORDER BY ALUNO.NOME) AS "INTEGRANTES"
  FROM T_GRUPO GRUPO
  JOIN T_ALUNO ALUNO ON GRUPO.ID_ALUNO = ALUNO.ID_ALUNO
  -- WHERE GRUPO.ID_TCC = 1
  GROUP BY GRUPO.ID_TCC
) ALUNOS ON TCC.ID_TCC = ALUNOS.ID_TCC
JOIN T_BANCA BANCA ON TCC.ID_TCC = BANCA.ID_TCC
JOIN T_PROFESSOR PROFESSOR ON BANCA.ID_PROFESSOR = PROFESSOR.ID_PROFESSOR
JOIN T_PROFESSOR ORIENTADOR ON TCC.ID_ORIENTADOR = ORIENTADOR.ID_PROFESSOR
-- WHERE GRUPO.ID_TCC = 1
GROUP BY TCC.TITULO, ALUNOS.INTEGRANTES, ORIENTADOR.NOME;
