CREATE TABLE ESTADO (
    UF CHAR(2) PRIMARY KEY,
    NOME VARCHAR(120) NOT NULL,
    CONSTRAINT UQ_NOME_ESTADO UNIQUE(NOME)
);
 
CREATE TABLE CIDADE (
    ID NUMBER(5) PRIMARY KEY,
    NOME VARCHAR2(120) NOT NULL,
    UF CHAR(2) NOT NULL,
    CONSTRAINT FK_CIDADE_ESTADO FOREIGN KEY(UF) REFERENCES ESTADO(UF)
);

CREATE TABLE ESPECIALIDADE (
    ID_ESPECIALIDADE NUMBER(3) PRIMARY KEY,
    NOME VARCHAR2(120) NOT NULL,
    CONSTRAINT UQ_NOME_ESP UNIQUE(NOME)
 );

CREATE TABLE MEDICO (
    ID_MEDICO NUMBER(10) PRIMARY KEY,
    NOME VARCHAR(120) NOT NULL,
    CRM VARCHAR2(30) NOT NULL,
    DT_NASC DATE NOT NULL,
    GENERO CHAR(1) NOT NULL,
    ATIVO CHAR(1) NOT NULL,
    ID_ESPECIALIDADE NUMBER(3) NOT NULL,
    CONSTRAINT UQ_CRM_MED UNIQUE(CRM),
    CONSTRAINT CK_GENERO_MED CHECK (GENERO IN ('M', 'F')),
    CONSTRAINT CK_ATIVO_MED CHECK (ATIVO IN ('S', 'N')),
    CONSTRAINT FK_MED_ESP FOREIGN KEY(ID_ESPECIALIDADE) REFERENCES ESPECIALIDADE(ID_ESPECIALIDADE)
);

CREATE TABLE PACIENTE (
    ID_PACIENTE NUMBER(5) PRIMARY KEY,
    CPF VARCHAR2(14) NOT NULL,
    NOME VARCHAR2(120) NOT NULL,
    DT_NASC DATE NOT NULL,
    GENERO CHAR(1) NOT NULL,
    CIDADE NUMBER(5) NOT NULL,
    CONSTRAINT UQ_CPF UNIQUE(CPF),
    CONSTRAINT CK_GENERO_PAC CHECK (GENERO IN ('M', 'F')),
    CONSTRAINT FK_PAC_CIDADE FOREIGN KEY (CIDADE) REFERENCES CIDADE(ID)
);


CREATE TABLE CONSULTA (
    DATA_HORA DATE,
    TIPO_CONSULTA CHAR(1) NOT NULL,
    STATUS CHAR(1) NOT NULL,
    OBS VARCHAR2(4000),
    ID_MEDICO NUMBER(10) NOT NULL,
    ID_PACIENTE NUMBBER (10) NOT NULL,
    CONSTRAINT CK_STATUS_CONS CHECK (STATUS IN ('A', 'C', 'R')),
    CONSTRAINT CK_TIPO_CONS CHECK (TIPO_CONSULTA IN ('C', 'R')),
    CONSTRAINT PK_CONS PRIMARY KEY (ID_PACIENTE, ID_MEDICO, DATA_HORA),
    CONSTRAINT FK_PAC_CONS FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID_PACIENTE),
    CONSTRAINT FK_MED_CONS FOREIGN KEY (ID_MEDICO) REFERENCES MEDICO(ID_MEDICO)
  );
  