CREATE TABLE PRODUTO (
  ID_PROD NUMBER(5) PRIMARY KEY,
  NOME VARCHAR2(12) NOT NULL,
  PRECO NUMBER(5,2) NOT NULL,
  DT_ULT_VENDA DATE,
  DT_ULT_COMPRA DATE,
  OBS VARCHAR2(1000),
  ATIVO CHAR(1) NOT NULL,
  CONSTRAINT CK_ATIVO_PRODUTO CHECK (ATIVO IN ('S', 'N'))
  );
                                          